print("Welcome Average and Grade Stats App")
name = input("\nWhat is your name : ").title()
n = int(input("How many grades do you want to enter : "))
grades = []
for i in range(n):
    grades.append(int(input("Enter Grade:")))
sort_grade = grades.copy()
sort_grade.sort(reverse=True)
print("\nGrade from Highest to Lowest:")
for i in range(n):
    print("\t" + str(sort_grade[i]))
print("\n" + name + "'s Grade Summary:")
print("\tTotal Number of Grades: " + str(len(grades)))
print("\tHighest Grades: " + str(sort_grade[0]))
print("\tLowest Grades: " + str(sort_grade[-1]))
old_average = sum(sort_grade) / len(grades)
print("\tAverage: " + str(old_average))
desired_average = float(input("\nWhat is your desired average: "))
print("\nGood Luck! "+name)
mark_needed = (desired_average * (n + 1)) - sum(grades)
print("You will need to score " + str(mark_needed) + " on your next assignment to earn a " + str(desired_average) +
      " average")
print("Lets see what your average could have been if you scored better/worse on a assignment.")
removed_grade = int(input("What grade would you like to change: "))
grades.remove(removed_grade)
grades.append(int(input("What grade would you like to change instead of " + str(removed_grade) + ": ")))
sort_grade2 = grades.copy()
sort_grade2.sort(reverse=True)
print("\nNew Grades from Highest to Lowest:")
for i in range(n):
    print("\t" + str(sort_grade2[i]))
print("\n" + name + "'s New Grade Summary:")
print("\tTotal Number of Grades: " + str(len(grades)))
print("\tHighest Grades: " + str(sort_grade2[0]))
print("\tLowest Grades: " + str(sort_grade2[-1]))
new_average = sum(sort_grade2) / len(grades)
print("\tAverage: " + str(new_average))
print("Your New average would be " + str(new_average) + " compared to your real average of " + str(old_average))
print("That is change of " + str(new_average - old_average) + "points!")
print("But your Original is still the same!")
print(sort_grade)
print("You should go ask for extra credits")
