print("Welcome to Favorite Teacher Program")
teachers = []
teachers.append(input("\nWho is your First Favorite Teacher : ").title())
teachers.append(input("Who is your Second Favorite Teacher : ").title())
teachers.append(input("Who is your Third Favorite Teacher : ").title())
teachers.append(input("Who is your Fourth Favorite Teacher : ").title())
print("\nYour favorite teacher ranked are : " + str(teachers))
print("Your favorite teacher alphabetically are : " + str(sorted(teachers)))
print("Your favorite teacher reverse alphabetically are : " + str(sorted(teachers, reverse=True)))
print("\nYour top two favorite teachers are : " + str(teachers[0]) + " and "+str(teachers[1]))
print("Your top next two favorite teachers are : " + str(teachers[2]) + " and "+str(teachers[3]))
print("Your last favorite teacher is : " + str(teachers[-1]))
print("You have total of " + str(len(teachers)) + " favorite teachers")
print("\nOops, " + teachers[0] + " is no longer your first favorite teacher", end=".")
# teachers.append(teachers.pop(0))
teachers.insert(0, input("Who is your new FAVORITE teacher: ").title())
print("\nYour favorite teacher ranked are : " + str(teachers))
print("Your favorite teacher alphabetically are : " + str(sorted(teachers)))
print("Your favorite teacher reverse alphabetically are : " + str(sorted(teachers, reverse=True)))
print("\nYour top two favorite teachers are : " + str(teachers[0]) + " and "+str(teachers[1]))
print("Your top next two favorite teachers are : " + str(teachers[2]) + " and "+str(teachers[3]))
print("Your last favorite teacher is : " + str(teachers[-1]))
print("You have total of " + str(len(teachers)) + " favorite teachers")
print("\nYou have decided you no longer like a teacher", end=".")
# teachers.append(teachers.pop(0))
teachers.remove(input("Which teacher would u like to remove from the list: ").title())
print("\nYour favorite teacher ranked are : " + str(teachers))
print("Your favorite teacher alphabetically are : " + str(sorted(teachers)))
print("Your favorite teacher reverse alphabetically are : " + str(sorted(teachers, reverse=True)))
print("\nYour top two favorite teachers are : " + str(teachers[0]) + " and "+str(teachers[1]))
print("Your top next two favorite teachers are : " + str(teachers[2]) + " and "+str(teachers[3]))
print("Your last favorite teacher is : " + str(teachers[-1]))
print("You have total of " + str(len(teachers)) + " favorite teachers")
