print("Welcome to Grade Sorter App")
grades=[]
grades.append(int(input("What is your First Grade (0-100) : ")))
grades.append(int(input("What is your Second Grade (0-100) : ")))
grades.append(int(input("What is your Third Grade (0-100) : ")))
grades.append(int(input("What is your Fourth Grade (0-100) : ")))
print("Your grades are : " + str(grades))
print("Your Grade from highest to lowest are : " + str(sorted(grades,reverse=True)))
grades.sort(reverse=True)
print("Lowest to grade will be Droped now")
print("Removing grade : " + str(grades.pop()))
print("Removing grade : " + str(grades.pop()))
grades.sort()
print("Your remaining grades are : " + str(grades))
print("Nice Work!   Your highest grade is :" + str(grades[-1]))
